version: '3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  catalog:
    image: acme/catalog:1.0
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - "traefik.http.routers.catalog.rule=Host(`catalog.acme.local`)"

  eshop:
    image: acme/eshop:1.0
    labels:
      - traefik.enable=true
      - traefik.port=5000
      - "traefik.http.routers.eshop.rule=Host(`eshop.acme.local`)"
